In [1]:
import numpy as np

In [2]:
# making array
a = np.array([1,2,3])
a


array([1, 2, 3])

In [3]:
# making array of zeros
np.zeros(6)

# making array of ones
np.ones(6)

# making random array
np.empty(3, order='F')

# making array with range
cth = np.arange(5,10)
cth

array([5, 6, 7, 8, 9])

In [4]:
# appending 2 or more array
np.append(cth, [1,2])

# deleting element of array by index
np.delete(cth, 0)

# cth =np.append(cth, [1,2,10])
np.sort(cth)

array([5, 6, 7, 8, 9])

In [5]:
# multi dimension array
array_example = np.array([
   [   [0,1,2,3],
       [4,5,6,7]],
   [   [0,1,2,3],
       [4,5,6,7]],
   [   [0,1,2,3],
       [4,5,6,7]],
])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [6]:
# show array dimension
print(array_example.ndim)

# show array total element
print(array_example.size)

# show array total element
print(array_example.shape)


3
24
(3, 2, 4)


In [7]:
array_example = np.array(
   [   [0,1,2,3],
       [4,5,6,7]],
)
array_example.shape
array_example.ndim
array_example.size

8

In [8]:
a = np.arange(16)
# reshaping an array
b = a.reshape(16,1)
b

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [9]:
display(a)

# add a dimension to an existing array
a2 = a[np.newaxis]
display(a2)
a3 = a2[np.newaxis]
display(a3)

row_vector = a[:,np.newaxis]
row_vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [10]:
a = np.arange(5)
display(a)
display(a.shape)

# expanding dimension
b = np.expand_dims(a, axis=0)
display(b)
display(b.shape)

array([0, 1, 2, 3, 4])

(5,)

array([[0, 1, 2, 3, 4]])

(1, 5)

In [11]:
a

array([0, 1, 2, 3, 4])

In [12]:
# slicing array by index
print(a[2])
print(a[:3])
print(a[::-1])
print(a[-2:])

2
[0 1 2]
[4 3 2 1 0]
[3 4]


In [13]:
array_example

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
# slicing array with condition
array_example[array_example >= 5]

array([5, 6, 7])

In [15]:
five_up = (array_example >= 5)
array_example[five_up]

array([5, 6, 7])

In [16]:
array_example[array_example%2==0]

array([0, 2, 4, 6])

In [17]:
# slicing using and
array_example[(array_example%2==0) & (array_example > 3)]
# slicing using or
array_example[(array_example%2==0) | (array_example > 3)]

array([0, 2, 4, 5, 6, 7])

In [18]:
a = np.arange(1,11)
b = a[3:8]
b

array([4, 5, 6, 7, 8])

In [19]:
a1 = np.array(
   [   [0,1,],
       [4,5,]])
a2 = np.array(
   [   [2,3,],
       [6,7,]])

In [20]:
# stacking vertically
np.vstack((a1, a2))

array([[0, 1],
       [4, 5],
       [2, 3],
       [6, 7]])

In [21]:
# stacking horizontally
np.hstack((a1, a2))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
display(a)
a2 = a[np.newaxis]
a4 = np.vstack((a2,a2))
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [23]:
# splitting array horizontally
np.hsplit(a4, 5)

[array([[1, 2],
        [1, 2]]),
 array([[3, 4],
        [3, 4]]),
 array([[5, 6],
        [5, 6]]),
 array([[7, 8],
        [7, 8]]),
 array([[ 9, 10],
        [ 9, 10]])]

In [24]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
a = np.arange(3)
b = np.arange(4,7)
print(a)
print(b)

# basic array operations 
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[0 1 2]
[4 5 6]
[4 6 8]
[-4 -4 -4]
[ 0  5 12]
[0.         0.2        0.33333333]


In [28]:
a3

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [29]:
a3.sum()

120

In [30]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
# sum with axis
print(c.sum(axis = 0))
print(c.sum(axis = 1))

[15 18 21 24]
[10 26 42]


In [32]:
print(a)
print(a * 1.6)

[0 1 2]
[0.  1.6 3.2]


In [33]:
# error
z = np.array([1,2,'z'])
z *15

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U11'), dtype('int32')) -> None

In [34]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
print(c.min())
print(c.max())
print(c.sum())
print(c.std())
print(c.min(axis = 1))
print(c.max(axis = 0))

1
12
78
3.452052529534663
[1 5 9]
[ 9 10 11 12]


In [36]:
# making matrix 
z = np.zeros((6,2))
o = np.ones((6,2))
r = np.random.random((6,2))
print(z)
print(o)
print(r)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0.63555502 0.68961974]
 [0.82858161 0.19081459]
 [0.63353931 0.95939913]
 [0.15664487 0.24360443]
 [0.42773023 0.14883227]
 [0.98546581 0.84597175]]


In [37]:
r + o

array([[1.63555502, 1.68961974],
       [1.82858161, 1.19081459],
       [1.63353931, 1.95939913],
       [1.15664487, 1.24360443],
       [1.42773023, 1.14883227],
       [1.98546581, 1.84597175]])

In [38]:
a1 = np.array([[0,1],[4,5], [7,8]])
print(a1)
a2 = np.array([[0,1,2],[4,5,6]])
print(a2)

[[0 1]
 [4 5]
 [7 8]]
[[0 1 2]
 [4 5 6]]


In [39]:
np.dot(a1,a2)

array([[ 4,  5,  6],
       [20, 29, 38],
       [32, 47, 62]])

In [40]:
# slicing matrix
a1 = np.array([[1,2],[3,4], [5,6]])
print(a1)
print(a1[0])
print(a1[2])
print(a1[0:2])
print(a1[0,1])
print(a1[0][1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[5 6]
[[1 2]
 [3 4]]
2
2


In [41]:
# transforming shape
display(a1)
print(a1.shape)
print(a1.T)
print(a1.T.shape)

array([[1, 2],
       [3, 4],
       [5, 6]])

(3, 2)
[[1 3 5]
 [2 4 6]]
(2, 3)


In [42]:
a = np.arange(6)

In [43]:
a2 = a[np.newaxis]
a2.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [49]:
a3 = a2.reshape(-1,3)
a3

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
# flatten multidimension array into 1D array
a4 = a3.flatten()
print(a4)
print(np.delete(a4, 1))
print(a3)

[0 1 2 3 4 5]
[0 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [51]:
a4 = a3.ravel()
print(a4)
print(np.delete(a4, 1))
print(a3)

[0 1 2 3 4 5]
[0 2 3 4 5]
[[0 1 2]
 [3 4 5]]
